### PR TITLE
Update swift 4.0

### PR DESCRIPTION
**Pull request by pjcau**

### CODE REVIEW

**Comment by pjcau** [comment]
Hi, 
I updated a method and the swift flags to 4.0. This to update this framework and this case pass my test ;)

Bye

**Comment by regexident** [comment]
Thanks, @pjcau!

**Comment by pjcau** [comment]
Thank, 

Can you upgrade the pod to swift4, so we can use it.

BR 
J

**Comment by regexident** [comment]
@pjcau 👉🏻 https://github.com/mrackwitz/Version/pull/27 🙂

Will publish to CocoaPods once tests succeed.

**Comment by pjcau** [comment]
👍

Inviato da iPhone

**Comment by regexident** [comment]
See 0.6.1 on Cocoapods. 🙂

**Comment by pjcau** [comment]
Thank a lot

J

Inviato da iPhone

**Pull request merged**
