### PR TITLE
Optional version from string representative unless a string literal

### PR DESCRIPTION
**Pull request by twodayslate**
Fix for #44

### CODE REVIEW

**Comment by regexident** [comment]
Thanks!

**Comment by wearhere** [comment]
Hey folks, these changes seem to suggest that parsing could fail when calling `init?(_ value: String)` directly (since that was changed to return an optional) but that parsing would be guaranteed to succeed when initializing a version from a literal (since that was changed to force unwrap the return). Wouldn't it be safer for the literal initializer to return an optional as well?

**Comment by twodayslate** [comment]
I assumed the string initialization was checked at runtime but that is probably incorrect given your post.

A `preconditionFailure` should probably be added?

**Comment by regexident** [comment]
`ExpressibleByStringLiteral` requires `init(stringLiteral value: Self.StringLiteralType)`.  
As such there is no way to make the literal return an optional.

When initializing a version from a literal you are the one responsible to make sure it's valid semver.

**Comment by wearhere** [comment]
Makes sense to me! The [clarification](https://github.com/mrackwitz/Version/commit/fa8fd0d93bd3a6b3054d6835acbd06c38d4f4d5f#diff-04c6e90faac2675aa89e2176d2eec7d8R36) in the README looks good too, thanks.

**Pull request merged**
